### ISSUE TITLE
Website!

### ISSUE THREAD

**Issue by RealAAbraham** [xcodz-dot/xcodz-dot#1]
You need some help with your website?

**Comment by xcodz-dot** [comment]
Well thanks, but the thing is i am facing no problems (this is just a profile). 😄 Thanks for thinking about that

**Comment by xcodz-dot** [comment]
My website lives in this repo https://github.com/xcodz-dot/xcodz-dot.github.io

Also, it will be great if you would like to help me in the documentation for this [project](https://github.com/xcodz-dot/denver)

**Comment by xcodz-dot** [comment]
I just found out that i accidently deleted it.
